FROM node:16.16.0

# 不完全だから頼む
WORKDIR /usr/src/app
RUN yarn --update
RUN yarn create-next-app@12.2.3 precure --typescript

# https://github.com/tamanyan/ts-nextbook-app/blob/main/package.json

# WORKDIR /usr/app/precure